
language: python

python:
 - "3.5"

addons:
  apt:
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

install:
  - "python -m pip install --upgrade numpy"
  - "python -m pip install --upgrade pandas"
  - "python -m pip install pyproj"
  - "python -m pip install pytest-cov"
  - "python -m pip install coveralls>=1.1"
  - "pip install -e src/"

script:
  - pytest --cov=.

after_success:
  - coveralls
